# constants.py

SCREEN_SAVER_TIME_SECONDS = 60
AMP_OUTPUT_PIN_GPIO = 40
USB_PATH_LINUX = "/media"
USB_PATH_WINDOWS = "C:/Users/gs200/Desktop/Dzwonek"
SCHEDULE_PATH_LINUX = "/bellCache/schedule.json"
LOGS_PATH_LINUX = "/tmp/logs"
DEFAULT_BELL_INTERVAL = 1
MAX_BELLS = 40
